#new SID
SID = AKfycbyCCOTXQ3kjJZOJPTXLAmseKlZSKS5p0zdY2JZcHVhwlubbQjNTyNlJKMRoH8J1IheRyQ

#old SID
#SID = AKfycbye6akuTA_UHOqrdZJwC9utsK1FTnUJIxTLndGibFgyNVPa0xW4FEsygSPfVsuHjsIsCg

download:	
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=works" -O works.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=concerts" -O concerts.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=archives" -O archives.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=composers" -O composers.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=editions" -O editions.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=people" -O people.json
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=bibliography" -O bibliography.json
