#new SID
SID = AKfycbyCCOTXQ3kjJZOJPTXLAmseKlZSKS5p0zdY2JZcHVhwlubbQjNTyNlJKMRoH8J1IheRyQ

#old SID
#SID = AKfycbye6akuTA_UHOqrdZJwC9utsK1FTnUJIxTLndGibFgyNVPa0xW4FEsygSPfVsuHjsIsCg

download:	
	wget "https://script.google.com/macros/s/$(SID)/exec?sheet=archives" -O archives.json